language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t adityakadu12/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true adityakadu12/react-test npm test

after_success:
    - docker build -t adityakadu12/multi-client ./client
    - docker build -t adityakadu12/multi-nginx ./nginx
    - docker build -t adityakadu12/multi-server ./server
    - docker build -t adityakadu12/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take above built images and push to docker hub
    - docker push adityakadu12/muilt-client
    - docker push adityakadu12/muilt-nginx
    - docker push adityakadu12/muilt-server
    - docker push adityakadu12/muilt-worker
